# fly.toml app configuration file generated for trackthat-backend on 2026-09-11T11:03:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trackthat-backend'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[restart]]
  policy = "on-failure"